### ISSUE TITLE
Upload latest copy of Textbook PDF.

### ISSUE THREAD

**Issue by alvinjchitena** [Zim-Code-Org/Introduction-to-Programming-Python#1]

**Comment by alvinjchitena** [comment]
@BukhosiMoyo please upload the latest copy of the textbook inside [this folder.](https://github.com/Zim-Code-Org/Introduction-to-Programming-Python/tree/master/12-week%20Course/PDF%20File)

**Comment by BukhosiMoyo** [comment]
[ZimCode Textbook.pdf](https://github.com/Zim-Code-Org/Introduction-to-Programming-Python/files/4241415/ZimCode.Textbook.pdf)
