### ISSUE TITLE
Create slide templates

### ISSUE THREAD

**Issue by alvinjchitena** [Zim-Code-Org/Introduction-to-Programming-Python#14]
Create slide templates:
1. Zim Code cover slide
2. New lesson slide
3. New topic slide
4. Generic content slide
5. Video slide
6. Image slide
7. Code slide
8. Quiz/Question/Exercise slide
9. Homework slide
10. Reminder/Messages slide
11. End/Bye slide

**Comment by alvinjchitena** [comment]
I've developed a template for the slides. You can [view the template here](https://www.canva.com/design/DAD0wR1kBQU/7lVDeuhRvqu8giMtKaS-6w/view?utm_content=DAD0wR1kBQU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink).

I will continue developing the template more once we start working on the Chapters and the slides associated with them. 

@BukhosiMoyo @mkphuthi, feel free to leave comments here.

**Comment by mkphuthi** [comment]
Are these templates easily usable in Powerpoint? I consider the slides as more of a base for tutors. They should feel free to edit them as they see fit in case there are slides they don't understand or if they feel like they need to edit them. Unlike the book I would prioritize the the tutor's ability to edit them easily than the "beauty" of the slides.

**Comment by alvinjchitena** [comment]
@mkphuthi  They are exportable to Powerpoint. I just use the site to get good templates. They are just templates. For example, if you want to demonstrate code in a code block, you just take the blank code block slide and add the contents. The template is for the aesthetics, not the content. It's just like a theme, so I don't anticipate that they will have trouble editing.

**Comment by alvinjchitena** [comment]
Slide template exists. Edits will be made for individual lesson slides.
